# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-08 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operate', '0002_auto_20170403_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswerlog',
            name='course',
        ),
        migrations.AddField(
            model_name='useranswerlog',
            name='mscore',
            field=models.IntegerField(default=-1, verbose_name='\u4eba\u5de5\u8bc4\u5206'),
        ),
        migrations.AddField(
            model_name='useranswerlog',
            name='paper_log_id',
            field=models.IntegerField(default=None, verbose_name='\u8bb0\u5f55id'),
        ),
        migrations.AlterField(
            model_name='useranswerlog',
            name='score',
            field=models.IntegerField(default=-1, verbose_name='\u5f97\u5206'),
        ),
    ]
