# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-08 12:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alloweduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassExcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='file/class_excle', verbose_name='\u6587\u4ef6\u540d')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('is_add', models.BooleanField(default=False, verbose_name='\u662f\u5426\u88ab\u5bfc\u5165\u6570\u636e\u5e93')),
            ],
            options={
                'verbose_name': '\u5bfc\u5165\u5b66\u751f\u4fe1\u606f\u6587\u4ef6',
                'verbose_name_plural': '\u5bfc\u5165\u5b66\u751f\u4fe1\u606f\u6587\u4ef6',
            },
        ),
        migrations.CreateModel(
            name='FileStroe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100, verbose_name='\u6587\u4ef6\u540d')),
                ('file_content', models.FileField(upload_to='file/%Y/%m/%d', verbose_name='\u6587\u4ef6')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('down_count', models.IntegerField(default=0, verbose_name='\u4e0b\u8f7d\u6b21\u6570')),
            ],
            options={
                'verbose_name': '\u8d44\u6599\u4e0b\u8f7d\u7ba1\u7406',
                'verbose_name_plural': '\u8d44\u6599\u4e0b\u8f7d\u7ba1\u7406',
            },
        ),
        migrations.DeleteModel(
            name='AllowedUser',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_classname',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(default=0, max_length=6),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_class',
            field=models.CharField(default='14\u4fe1\u7b972', max_length=20, verbose_name='\u73ed\u7ea7\u540d'),
        ),
    ]
