# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-25 07:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coures', '0002_paper_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPaperLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_name_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('status', models.IntegerField()),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('score', models.CharField(blank=True, max_length=225, null=True, verbose_name='\u5206\u6570')),
            ],
            options={
                'verbose_name': '\u8bd5\u9898\u5217\u8868',
                'verbose_name_plural': '\u8bd5\u9898\u5217\u8868',
            },
        ),
        migrations.RemoveField(
            model_name='question',
            name='content',
        ),
        migrations.AlterField(
            model_name='paper',
            name='course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='coures.CourseList', verbose_name='\u6240\u5c5e\u8bfe\u7a0b'),
        ),
        migrations.AlterField(
            model_name='question',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coures.CourseList', verbose_name='\u8bfe\u7a0b'),
        ),
    ]
