# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-25 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coures', '0003_auto_20180725_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='content',
            field=models.TextField(default='', verbose_name='\u9898\u76ee\u5185\u5bb9'),
            preserve_default=False,
        ),
    ]
