# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-25 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coures', '0004_question_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='Question_class',
            field=models.TextField(default='\u64cd\u4f5c\u7cfb\u7edf', verbose_name='\u9898\u76ee\u7c7b\u522b'),
        ),
    ]
