# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-25 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coures', '0005_question_question_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='Question_degree',
            field=models.IntegerField(default=0, verbose_name='\u9898\u76ee\u96be\u5ea6'),
        ),
    ]
