# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-25 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coures', '0006_question_question_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='score_point',
            field=models.TextField(default='\u8fdb\u7a0b\u7ba1\u7406+5\u6b7b\u9501+5', verbose_name='\u5f97\u5206\u70b9\u5217\u8868'),
        ),
    ]
